** CONFRIMPAGE SUB

SUBROUTINE CONFIRMPAGE
COMMON MAINSECTIONWIDTH, DISPLAYSECTIONWIDTH, MAINSTARTLINE, MAINHEADER, MAINCOL
    COMMON OrderListArray, BackOrderListArray
    COMMON CustomerID
**SP-NEWTAB
**SP-CREATE SERVERDFLT NT

PRINTER ON;
PRINT CustomerID;

**GOSUB CONFRIMCUSTOMERINFO
PRINTER CLOSE ;


